### ISSUE TITLE
Why publishing a kanged repo?

### ISSUE THREAD

**Issue by Itz-fork** [AsmSafone/MegaDL-Bot#2]
Hey, Recently I found that you kanged [My Mega.nz Repo](https://github.com/Itz-fork/Mega.nz-Bot) **Without Credits!** I'm nicely asking you to give credits to [Me](https://github.com/Itz-fork). And I guess you didn't read the [warning comment](https://github.com/Itz-fork/Mega.nz-Bot/blob/02bb619cab769030971d27707eb3b8ac014d3616/megadl/mega_dl.py#L2) in My Repo. Please read it once again if you really love your dad :ok_hand:  . Also please note that I have added [GPL 3.0 Licence](https://github.com/Itz-fork/Mega.nz-Bot/blob/main/LICENSE) in my repository. You still have a chance to give credits to me else i can do a copyright claim to this repo

**Comment by raveen2003** [comment]
**NICE EXPECTED !!**

**Comment by Achu2234** [comment]
> EXPECTED

What  EXPECTED

**Comment by Itz-fork** [comment]
> What EXPECTED

He must add credits bruh! and i found that his Custom caption and Thumbnail functions are also kanged from another repository without credits. lol :rofl:

**Comment by AsmSafone** [comment]
Lol. 🤣🤣
